/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RotationPanel.java
 *
 * Created on 2009-12-07, 14:58:47
 */

package transformers.gui;

import javax.swing.InputVerifier;
import javax.swing.JComponent;
import javax.swing.JSpinner;

/**
 *
 * @author szymon
 */
public class RotationPanel extends javax.swing.JPanel {
    InputVerifier degreeVerifier;
    /** Creates new form RotationPanel */
    public RotationPanel() {
        degreeVerifier = new InputVerifier() {

            @Override
            public boolean verify(JComponent input) {
                int value = -1;
                JSpinner spinner = null;
                if (input != null && input instanceof JSpinner) {
                    spinner = (JSpinner) input;
                    value = (Integer) spinner.getValue();

                    if (value < 0) value = 360;
                    else if (value > 360) value = 0;
                    spinner.setValue(Integer.valueOf(value));
                }
                return true;
            }
        };
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jSlider1 = new javax.swing.JSlider();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jSpinner2 = new javax.swing.JSpinner();
        jSlider2 = new javax.swing.JSlider();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel1.setLayout(new java.awt.GridLayout());

        jLabel1.setText("Rotacja x:");
        jPanel1.add(jLabel1);

        jSpinner1.setEditor(new javax.swing.JSpinner.NumberEditor(jSpinner2, ""));
        jPanel1.add(jSpinner1);

        add(jPanel1);

        jSlider1.setMaximum(360);
        jSlider1.setValue(0);
        add(jSlider1);

        jSeparator1.setMinimumSize(new java.awt.Dimension(10, 10));
        add(jSeparator1);

        jPanel2.setLayout(new java.awt.GridLayout());

        jCheckBox1.setText("Inna dla y:");
        jPanel2.add(jCheckBox1);

        jSpinner2.setEditor(new javax.swing.JSpinner.NumberEditor(jSpinner2, ""));
        jSpinner2.setEnabled(false);
        jPanel2.add(jSpinner2);

        add(jPanel2);

        jSlider2.setMaximum(360);
        jSlider2.setValue(0);
        jSlider2.setEnabled(false);
        add(jSlider2);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSlider jSlider2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    // End of variables declaration//GEN-END:variables

}
