/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ToolPanel.java
 *
 * Created on 2009-12-07, 14:48:33
 */

package transformers.gui;

import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author szymon
 */
public class ToolPanel extends javax.swing.JPanel {
    private String title;

    /** Creates new form ToolPanel */
    public ToolPanel(String title, JPanel panel) {
        this.title = title;
        initComponents();
        this.add(panel, BorderLayout.CENTER);
    }

    public String getTitle() {
        return title;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBorder(javax.swing.BorderFactory.createTitledBorder(getTitle()));
        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
